version: "3.8"
services:
  mysql_srv:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laitteet
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      # Data persistence volume that allows to persist the data between container restarts
      - mysql_data:/var/lib/mysql
      # - "./config/my.conf:/etc/mysql/conf.d/config-file.cnf"
      # - "./data:/var/lib/mysql:rw"

  phpmyadmin_srv:
    depends_on:
      - mysql_srv
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_ctr
    restart: always
    environment:
      PMA_HOST: mysql_srv
    ports:
      - 8080:80

  backend_srv:
    build:
      context: ./api
    depends_on:
      - mysql_srv
    environment:
      MYSQL_HOST_IP: mysql_srv
      MYSQL_USER: root
      MYSQL_DATABASE: laitteet
      MYSQL_PASSWORD: root
    ports:
      - 5000:5000
    volumes:
      - ./api:/api

  frontend_srv:
    build:
      context: ./web_tehtava3
    ports:
      - 3000:80
    volumes:
      - ./web_tehtava3:/web_tehtava3

volumes:
  mysql_data:
    driver: local
